# Numpy review homework

1. Make a numpy matrix from a Python list of lists...

In [2]:
import numpy as np
lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. Make a 3D numpy matrix from a Python list of lists of lists!

In [3]:
lists_of_lists = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
np.array(lists_of_lists)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

3. Create a 5x3 array of Gaussian random numbers. 

In [30]:
gaus = np.random.randn(5,3)
print(gaus)

[[ 1.06423433  0.56612222 -0.30626045]
 [-1.54374125  0.29574638  0.31381498]
 [-0.06003507  0.31892978 -0.79770786]
 [-0.724865    1.36611505  1.35239911]
 [ 1.970519   -0.30257936  0.33470478]]


4. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [39]:
for i in range(5):
    gaus[i]
    for j in range(3): 
        print(f"The value at row: {[i+1]} and column: {[j+1]} is {gaus[i,j]}")

The value at row: [1] and column: [1] is 1.0642343331214061
The value at row: [1] and column: [2] is 0.5661222217198899
The value at row: [1] and column: [3] is -0.30626044552525084
The value at row: [2] and column: [1] is -1.5437412491720597
The value at row: [2] and column: [2] is 0.29574638458506575
The value at row: [2] and column: [3] is 0.3138149766594593
The value at row: [3] and column: [1] is -0.06003506606467597
The value at row: [3] and column: [2] is 0.3189297751087124
The value at row: [3] and column: [3] is -0.7977078601227465
The value at row: [4] and column: [1] is -0.7248649961379671
The value at row: [4] and column: [2] is 1.366115048370097
The value at row: [4] and column: [3] is 1.352399106714507
The value at row: [5] and column: [1] is 1.9705189950434572
The value at row: [5] and column: [2] is -0.3025793559230522
The value at row: [5] and column: [3] is 0.3347047835028733


5. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

In [5]:
random_nums = 10 + 3 * np.random.randn(5,3)
print(random_nums)

[[ 8.17561006 13.84311728 13.08669988]
 [ 6.3730152  14.08190314 13.26248189]
 [11.52449614 13.04444886  9.92407492]
 [ 9.15128479 10.72495887 12.06622937]
 [12.78531801 13.55492335 12.08482396]]


6. Count the number of values in your new array that are below 7.

In [25]:
below_sev = sum(random_nums < 7)
below_sev.sum()

1

7. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

In [28]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

8. Get the second and third rows of your array created in #5.

In [12]:
random_nums[1:3, :]

array([[ 6.3730152 , 14.08190314, 13.26248189],
       [11.52449614, 13.04444886,  9.92407492]])

9. Compute the mean of the columns of your array created in #5.

In [20]:
random_nums.mean(0)

array([ 9.60194484, 13.0498703 , 12.084862  ])